#!/bin/bash
# ============================================
# COMPLETE NGINX FIX FOR JUSTACHAT VPS
# Fixes: storage snippet, config issues, duplicates
# Run: sudo bash /var/www/justachat/public/vps-deploy/fix-nginx-complete.sh
# ============================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo "============================================"
echo -e "${CYAN}  COMPLETE NGINX FIX FOR JUSTACHAT${NC}"
echo "============================================"
echo ""

DEPLOY_DIR="${DEPLOY_DIR:-/var/www/justachat}"
DOCKER_DIR="${DOCKER_DIR:-/home/unix/supabase/docker}"

# ============================================
# STEP 1: Find the nginx config
# ============================================
echo -e "${YELLOW}[1] Finding nginx config...${NC}"

NGINX_CONF=""
# Check common locations
for conf in /etc/nginx/sites-enabled/justachat \
            /etc/nginx/sites-enabled/justachat.net \
            /etc/nginx/sites-available/justachat \
            /etc/nginx/sites-available/justachat.net \
            /etc/nginx/conf.d/justachat.conf; do
  if [ -f "$conf" ]; then
    NGINX_CONF="$conf"
    break
  fi
done

if [ -z "$NGINX_CONF" ]; then
  echo -e "${YELLOW}No standard config found, searching...${NC}"
  NGINX_CONF=$(grep -rl "justachat.net" /etc/nginx/sites-enabled/ 2>/dev/null | head -1)
  if [ -z "$NGINX_CONF" ]; then
    NGINX_CONF=$(grep -rl "justachat.net" /etc/nginx/conf.d/ 2>/dev/null | head -1)
  fi
fi

if [ -z "$NGINX_CONF" ] || [ ! -f "$NGINX_CONF" ]; then
  echo -e "${RED}ERROR: Cannot find nginx config for justachat.net${NC}"
  echo "Checked: sites-enabled, sites-available, conf.d"
  echo ""
  echo "List your nginx configs:"
  ls -la /etc/nginx/sites-enabled/ 2>/dev/null || true
  ls -la /etc/nginx/conf.d/ 2>/dev/null || true
  exit 1
fi

echo -e "${GREEN}✓ Found config: $NGINX_CONF${NC}"

# ============================================
# STEP 2: Get ANON_KEY for storage snippet
# ============================================
echo ""
echo -e "${YELLOW}[2] Getting ANON_KEY...${NC}"

ANON_KEY=""
# Try Docker .env
if [ -f "$DOCKER_DIR/.env" ]; then
  ANON_KEY=$(grep -E "^ANON_KEY=" "$DOCKER_DIR/.env" | cut -d'=' -f2- | tr -d '"' | tr -d "'")
fi

# Fallback: frontend .env
if [ -z "$ANON_KEY" ] && [ -f "$DEPLOY_DIR/.env" ]; then
  ANON_KEY=$(grep -E "^VITE_SUPABASE_PUBLISHABLE_KEY=" "$DEPLOY_DIR/.env" | cut -d'=' -f2- | tr -d '"' | tr -d "'")
fi

if [ -z "$ANON_KEY" ]; then
  echo -e "${RED}ERROR: Could not find ANON_KEY${NC}"
  exit 1
fi

echo -e "${GREEN}✓ Found ANON_KEY (${ANON_KEY:0:20}...)${NC}"

# ============================================
# STEP 3: Create storage snippet
# ============================================
echo ""
echo -e "${YELLOW}[3] Creating storage snippet...${NC}"

SNIPPET_FILE="/etc/nginx/snippets/storage-public.conf"
mkdir -p /etc/nginx/snippets

cat > "$SNIPPET_FILE" << EOF
# Public storage bypass - inject apikey for Kong
# Auto-generated by fix-nginx-complete.sh on $(date)
location ~ ^/storage/v1/object/public/ {
    proxy_pass http://127.0.0.1:8000;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    
    # Inject anon key for Kong - public objects don't need user auth
    proxy_set_header apikey '$ANON_KEY';
    
    # Cache headers for images
    proxy_cache_valid 200 1h;
    add_header Cache-Control "public, max-age=3600";
}
EOF

chmod 644 "$SNIPPET_FILE"
echo -e "${GREEN}✓ Created $SNIPPET_FILE${NC}"

# ============================================
# STEP 4: Backup current config
# ============================================
echo ""
echo -e "${YELLOW}[4] Backing up current config...${NC}"

BACKUP="$NGINX_CONF.bak.$(date +%Y%m%d%H%M%S)"
cp "$NGINX_CONF" "$BACKUP"
echo -e "${GREEN}✓ Backed up to $BACKUP${NC}"

# ============================================
# STEP 5: Check if snippet already included
# ============================================
echo ""
echo -e "${YELLOW}[5] Checking if snippet already included...${NC}"

if grep -q "include.*snippets/storage-public.conf" "$NGINX_CONF"; then
  echo -e "${GREEN}✓ Snippet already included${NC}"
else
  echo -e "${YELLOW}Adding snippet include...${NC}"
  
  # Find the line number of "listen 443 ssl" to insert after
  SSL_LINE=$(grep -n "listen 443 ssl" "$NGINX_CONF" | head -1 | cut -d: -f1)
  
  if [ -n "$SSL_LINE" ]; then
    # Insert after SSL line (within the server block)
    # Find a good insertion point - before the first location block
    FIRST_LOCATION=$(awk '/listen 443 ssl/,/location/ {if(/location/) print NR; exit}' "$NGINX_CONF")
    
    if [ -n "$FIRST_LOCATION" ]; then
      # Insert before first location
      sed -i "${FIRST_LOCATION}i\\
\\
    # Public storage - inject apikey for Kong\\
    include snippets/storage-public.conf;" "$NGINX_CONF"
      echo -e "${GREEN}✓ Inserted snippet before first location block${NC}"
    else
      # Fallback: insert after ssl_protocols line
      sed -i '/ssl_protocols/a\
\
    # Public storage - inject apikey for Kong\
    include snippets/storage-public.conf;' "$NGINX_CONF"
      echo -e "${GREEN}✓ Inserted snippet after ssl_protocols${NC}"
    fi
  else
    echo -e "${RED}Could not find SSL server block - manual edit required${NC}"
  fi
fi

# ============================================
# STEP 6: Clean up backup files in nginx dirs
# ============================================
echo ""
echo -e "${YELLOW}[6] Cleaning up old backup files...${NC}"

CLEANED=0
for dir in /etc/nginx/sites-enabled /etc/nginx/sites-available /etc/nginx/snippets /etc/nginx/conf.d; do
  if [ -d "$dir" ]; then
    for pattern in "*.bak.*" "*.backup" "*.old" "*~" "*.save" "*.orig" "*.dpkg-*"; do
      for f in "$dir"/$pattern; do
        if [ -f "$f" ]; then
          rm -f "$f"
          CLEANED=$((CLEANED + 1))
        fi
      done
    done
  fi
done

if [ "$CLEANED" -gt 0 ]; then
  echo -e "${GREEN}✓ Removed $CLEANED old backup files${NC}"
else
  echo -e "${GREEN}✓ No old backups to clean${NC}"
fi

# ============================================
# STEP 7: Check for duplicate location blocks
# ============================================
echo ""
echo -e "${YELLOW}[7] Checking for duplicate blocks...${NC}"

STORAGE_COUNT=$(grep -c "location.*storage/v1" "$NGINX_CONF" 2>/dev/null || echo "0")
if [ "$STORAGE_COUNT" -gt 2 ]; then
  echo -e "${YELLOW}⚠ Found $STORAGE_COUNT storage location blocks - may have duplicates${NC}"
else
  echo -e "${GREEN}✓ No duplicate storage blocks${NC}"
fi

# ============================================
# STEP 8: Ensure realtime websocket config
# ============================================
echo ""
echo -e "${YELLOW}[8] Checking realtime/websocket config...${NC}"

if grep -q "proxy_buffering off" "$NGINX_CONF"; then
  echo -e "${GREEN}✓ Proxy buffering disabled (good for websockets)${NC}"
else
  echo -e "${YELLOW}⚠ Consider adding 'proxy_buffering off' for realtime stability${NC}"
fi

# ============================================
# STEP 9: Test nginx configuration
# ============================================
echo ""
echo -e "${YELLOW}[9] Testing nginx configuration...${NC}"

if nginx -t 2>&1; then
  echo -e "${GREEN}✓ Nginx config test passed${NC}"
else
  echo -e "${RED}ERROR: Nginx config test FAILED${NC}"
  echo "Restoring backup..."
  cp "$BACKUP" "$NGINX_CONF"
  nginx -t
  exit 1
fi

# ============================================
# STEP 10: Reload nginx
# ============================================
echo ""
echo -e "${YELLOW}[10] Reloading nginx...${NC}"

systemctl reload nginx
echo -e "${GREEN}✓ Nginx reloaded${NC}"

# ============================================
# STEP 11: Test storage access
# ============================================
echo ""
echo -e "${YELLOW}[11] Testing storage access...${NC}"
sleep 1

# Test public storage endpoint
TEST_URL="https://justachat.net/storage/v1/object/public/avatars/"
TEST_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$TEST_URL" 2>/dev/null || echo "000")

if [ "$TEST_CODE" = "200" ] || [ "$TEST_CODE" = "404" ] || [ "$TEST_CODE" = "400" ]; then
  echo -e "${GREEN}✓ Public storage accessible (HTTP $TEST_CODE)${NC}"
else
  echo -e "${YELLOW}⚠ Storage returned HTTP $TEST_CODE${NC}"
fi

# ============================================
# SUMMARY
# ============================================
echo ""
echo "============================================"
echo -e "${GREEN}  NGINX FIX COMPLETE${NC}"
echo "============================================"
echo ""
echo "Config: $NGINX_CONF"
echo "Snippet: $SNIPPET_FILE"
echo "Backup: $BACKUP"
echo ""
echo "Test image URLs should now load without 401 errors."
echo "If issues persist, check:"
echo "  - docker compose logs storage"
echo "  - Storage bucket 'avatars' has public SELECT policy"
echo ""
