-- Add comprehensive dating profile fields
ALTER TABLE public.dating_profiles
ADD COLUMN IF NOT EXISTS gender text,
ADD COLUMN IF NOT EXISTS seeking text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS height_cm integer,
ADD COLUMN IF NOT EXISTS weight_kg integer,
ADD COLUMN IF NOT EXISTS body_type text,
ADD COLUMN IF NOT EXISTS ethnicity text,
ADD COLUMN IF NOT EXISTS relationship_status text,
ADD COLUMN IF NOT EXISTS looking_for_type text,
ADD COLUMN IF NOT EXISTS has_children boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS wants_children text,
ADD COLUMN IF NOT EXISTS education text,
ADD COLUMN IF NOT EXISTS occupation text,
ADD COLUMN IF NOT EXISTS smoking text,
ADD COLUMN IF NOT EXISTS drinking text,
ADD COLUMN IF NOT EXISTS religion text,
ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS max_distance_km integer DEFAULT 100,
ADD COLUMN IF NOT EXISTS min_age integer DEFAULT 18,
ADD COLUMN IF NOT EXISTS max_age integer DEFAULT 99,
ADD COLUMN IF NOT EXISTS about_me text,
ADD COLUMN IF NOT EXISTS ideal_match text,
ADD COLUMN IF NOT EXISTS hobbies text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS zodiac text,
ADD COLUMN IF NOT EXISTS pets text,
ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS last_active timestamptz DEFAULT now(),
ADD COLUMN IF NOT EXISTS profile_complete boolean DEFAULT false;